USE [master]
GO

/****** Object:  Database [Clickstream]    Script Date: 05/21/2016 10:06:13 ******/
CREATE DATABASE [Clickstream] ON  PRIMARY 
( NAME = N'Clickstream', FILENAME = N'D:\RDSDBDATA\DATA\Clickstream.mdf' , SIZE = 12011584KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Clickstream_log', FILENAME = N'D:\RDSDBDATA\DATA\Clickstream_log.ldf' , SIZE = 19352192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clickstream].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Clickstream] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Clickstream] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Clickstream] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Clickstream] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Clickstream] SET ARITHABORT OFF 
GO

ALTER DATABASE [Clickstream] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Clickstream] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Clickstream] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Clickstream] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Clickstream] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Clickstream] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Clickstream] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Clickstream] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Clickstream] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Clickstream] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Clickstream] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Clickstream] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Clickstream] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Clickstream] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Clickstream] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Clickstream] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Clickstream] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Clickstream] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Clickstream] SET  READ_WRITE 
GO

ALTER DATABASE [Clickstream] SET RECOVERY FULL 
GO

ALTER DATABASE [Clickstream] SET  MULTI_USER 
GO

ALTER DATABASE [Clickstream] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Clickstream] SET DB_CHAINING OFF 
GO


USE [Clickstream]
GO

/****** Object:  Table [dbo].[clickstreamEventsLog]    Script Date: 05/21/2016 10:06:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[clickstreamEventsLog](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[timestamp] [datetime] NOT NULL,
	[received] [datetime] NOT NULL,
	[deviceId] [nvarchar](50) NOT NULL,
	[eventCode] [nvarchar](max) NOT NULL,
	[msoName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_clickstreamEventsLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


